theme: jekyll-theme-minimal
author: Jason Kautz
email: jdkautz4@gmail.com
description: >-
  Assistant Professor of Organization Behavior and Human Resource Management
social_links:
  - label: LinkedIn
  url: https://www.linkedin.com/in/jason-kautz-04942149/
  - label: CV
  url: /Kautz - CV 2025.pdf
